name: "Build"
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: buildah
    steps:
      - uses: actions/checkout@v4
      - name: Get Tags
        id: git_describe
        run: |
          echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Build image
        run: |
          echo "building ${{ vars.DOCKER_NAME }} ${{ env.GIT_TAG }}"
          buildah bud -t ${{ vars.DOCKER_NAME }}:${{ env.GIT_TAG }} .
      - name: Push image
        run: |
          buildah login -u lotlab_bot -p ${{ secrets.LOTLAB_BOT }} code.lotlab.org
          buildah tag ${{ vars.DOCKER_NAME }}:${{ env.GIT_TAG }} ${{ vars.DOCKER_NAME }}:latest
          buildah push ${{ vars.DOCKER_NAME }}:${{ env.GIT_TAG }}
          buildah push ${{ vars.DOCKER_NAME }}:latest
      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Kubernetes cluster"
          kubectl set image ${{ vars.K8S_RESOURCE }} ${{ vars.K8S_CONTAINER }}=${{ vars.DOCKER_NAME }}:${{ env.GIT_TAG }} --namespace=${{ vars.K8S_NS }}
          kubectl rollout status ${{ vars.K8S_RESOURCE }} --namespace=${{ vars.K8S_NS }}
